import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { LearningPath } from '../types';

export const generateMarkdownExport = (roadmap: LearningPath): string => {
  return `# ${roadmap.title} Learning Roadmap

**Duration:** ${roadmap.duration} months  
**Difficulty:** ${roadmap.difficulty}  
**Progress:** ${roadmap.progress}%

## Description
${roadmap.description}

## Learning Phases

${roadmap.phases
  .map(
    (phase, index) => `
### Phase ${index + 1}: ${phase.title}

**Duration:** ${phase.duration} weeks  
**Status:** ${phase.completed ? "✅ Completed" : "⏳ In Progress"}

#### Skills You'll Learn
${phase.skills.map((skill) => `- ${skill}`).join("\n")}

#### Learning Resources
${phase.resources
  .map(
    (resource) =>
      `- [${resource.title}](${resource.url}) (${resource.type}${
        resource.duration ? ` - ${resource.duration}` : ""
      })`
  )
  .join("\n")}

#### Milestone Project
${phase.project}

---
`
  )
  .join("")}

Generated by LearnPath AI - ${new Date().toLocaleDateString()}
`;
};

export const generateCSVExport = (roadmap: LearningPath): string => {
  const headers = ['Phase ID', 'Phase Title', 'Duration (Weeks)', 'Status', 'Skills', 'Resources', 'Project'];
  const rows = roadmap.phases.map(phase => [
    phase.id,
    phase.title,
    phase.duration,
    phase.completed ? 'Completed' : 'In Progress',
    phase.skills.join('; '),
    phase.resources.map(r => `${r.title} (${r.url})`).join('; '),
    phase.project
  ]);

  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.map(cell => `"${String(cell).replace(/"/g, '""')}"`).join(','))
  ].join('\n');

  return csvContent;
};

export const generatePDFExport = (roadmap: LearningPath) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Title
  doc.setFontSize(20);
  doc.setTextColor(41, 128, 185); // Blue color
  doc.text(roadmap.title + ' Roadmap', pageWidth / 2, 20, { align: 'center' });
  
  // Metadata
  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text(`Duration: ${roadmap.duration} months | Difficulty: ${roadmap.difficulty} | Progress: ${roadmap.progress}%`, pageWidth / 2, 30, { align: 'center' });
  
  // Description
  doc.setFontSize(10);
  doc.setTextColor(50);
  const splitDesc = doc.splitTextToSize(roadmap.description, pageWidth - 40);
  doc.text(splitDesc, 20, 40);

  let finalY = 40 + (splitDesc.length * 5) + 10;

  // Phases Table
  const tableData = roadmap.phases.map((phase, index) => [
      `Phase ${index + 1}: ${phase.title}\n(${phase.duration} weeks)`,
      phase.skills.join(', '),
      phase.resources.map(r => `• ${r.title}`).join('\n'),
      phase.project
  ]);

  autoTable(doc, {
    startY: finalY,
    head: [['Phase', 'Skills', 'Resources', 'Project']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [41, 128, 185], textColor: 255 },
    columnStyles: {
        0: { cellWidth: 35 }, // Phase
        1: { cellWidth: 45 }, // Skills
        2: { cellWidth: 55 }, // Resources
        3: { cellWidth: 'auto' } // Project
    },
    styles: { fontSize: 9, cellPadding: 3, overflow: 'linebreak' },
    didDrawPage: (data) => {
        // Footer
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text('Generated by LearnPath AI', pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });
    }
  });

  return doc;
};
